events {}

http {

    upstream auth_service {
        server auth-service:8001;
    }

    upstream candidate_service {
        server candidate-service:8002;
    }

    server {

        listen 80;

        location / {
            return 200 "Gateway Running";
        }

        location /auth/ {
            proxy_pass http://auth_service/;
        }

        location /candidates/ {
            proxy_pass http://candidate_service/;
        }

        location /admin/ {
            proxy_pass http://candidate_service/admin/;
        }

        location /health {
            return 200 "Gateway Healthy";
        }
    }
}