events {}

http {

    # ================= RATE LIMIT =================

    limit_req_zone $binary_remote_addr zone=auth_limit:10m rate=5r/s;
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=20r/s;

    upstream auth_service {
        server auth-service:8001;
    }

    upstream candidate_service {
        server candidate-service:8002;
    }

    server {

        listen 80;

        location / {
            return 200 "Gateway Running";
        }

        # ================= AUTH =================

        location /auth/ {

            limit_req zone=auth_limit burst=10 nodelay;

            proxy_pass http://auth_service/;
        }

        # ================= CANDIDATES =================

        location /candidates/ {

            limit_req zone=api_limit burst=20 nodelay;

            proxy_pass http://candidate_service/;
        }

        # ================= ADMIN =================

        location /admin/ {

            limit_req zone=api_limit burst=20 nodelay;

            proxy_pass http://candidate_service/admin/;
        }

        location /health {
            return 200 "Gateway Healthy";
        }
    }
}